name: build-ci
on: [push]
runs-on: self-hosted
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.6.0
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: lerna run min
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: lerna run test-cov
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ./packages/diffhtml/coverage/lcov.info
          base-path: ./packages/diffhtml
